version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: pizza-db
    environment:
      POSTGRES_DB: pizza_deliziosa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pizza-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=pizza_deliziosa
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - JWT_SECRET=pizza_deliziosa_secret_key_for_production
      - ALLOWED_ORIGINS=http://localhost:4200,http://localhost:80
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Angular frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pizza-frontend
    environment:
      - API_URL=http://backend:8080
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: 